on: 
  push:
  workflow_dispatch:
    

jobs:

  container-scan:
      runs-on: ubuntu-latest
      name: container scan

      steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: container-scan action step
          id: container-scan
          uses: ./
          with:
            vid: ${{ secrets.VID }}
            vkey: ${{ secrets.VKEY }}
            command: "scan" 
            type: "directory"
            source: "./"
            format: "github"
            debug: 1
            fail_build: false
#new added coded to convert the output
        # - name: Convert pipeline scan output to SARIF format
        #   id: convert
        #   uses: veracode/veracode-pipeline-scan-results-to-sarif@ff08ae5b45d5384cb4679932f184c013d34da9be
        #   with:
        #     # source-base-path-1: "^com/veracode:app/src/main/java/com/veracode"
        #     # source-base-path-2: "^WEB-INF:app/src/main/webapp/WEB-INF"
        #     pipeline-results-json: results.json
        # - uses: github/codeql-action/upload-sarif@v2
        #   with:
        #     # Path to SARIF file relative to the root of the repository
        #     sarif_file: veracode-results.sarif